version: "3"

networks:
  laravel:

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    container_name: app_simple_pointer
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel

  supervisor:
    build:
      context: .
      dockerfile: ./.docker/supervisor/Dockerfile
    container_name: supervisor
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - app
    ports:
      - "6001:6001"
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public:delegated
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
