name: Deploy

on:
  release:
    types: [published]

jobs:
  build:
    name: Deploy code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Fetch built assets from Artifacts # Rsync the compiled assests over using deployer
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extension-csv: mbstring, bcmath

      - name: Composer install
        run: composer install

      - name: Setup Deployer
      - name: Deploy
        uses: atymic/deployer-php-action@0.2.0
        with:
          ssh-private-key: ${{ secrets.LIGHTHSAIL_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Prod
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: dep deploy production --tag=${{ env.GITHUB_REF }} -vvv
