name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy .env
        run: cp .env.dusk.local .env

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.9.0 #https://github.com/shivammathur/setup-php
        with:
          php-version: 7.4
          Extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path:
            ${{ steps.composercache.outputs.dir }}
            # Use composer.json for key, if composer.lock is not committed.
            # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Run CS Fixer
        uses: OskarStark/php-cs-fixer-ga@2.16.4

      - name: Get npm cache directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install front-end dependencies
        run: |
          npm install
          npm run prod
          cat public/mix-manifest.json # See asset versions in log

      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public

      - name: Create DB and schemas
        run: |
          mkdir -p storage
          touch storage/database.sqlite
          php artisan migrate --seed

      - name: Run phpstan
        run: composer phpstan

      - name: Run PHPUnit tests
        env:
            DB_CONNECTION: sqlite
            DB_DATABASE: database.sqlite
        run: composer phpunit

      - name: Upgrade chrome driver
        run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

      - name: Run Laravel Server
        env:
          PUHSER_HOST: 127.0.0.1 # Set the pusher host for github actions
        run: php artisan serve > /dev/null 2>&1 &

      - name: Run Websockets Server
        run: php artisan websockets:serve > /dev/null 2>&1 &

      - name: Run dusk tests
        run: php artisan dusk

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: Download build assets
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.9.0 #https://github.com/shivammathur/setup-php
        with:
          php-version: 7.4
          Extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Composer install
        run: composer install

      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.LIGHTHSAIL_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Prod
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: dep deploy production --tag=${{ env.GITHUB_REF }} -vvv
