name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php-versions: [8.5]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-composer-${{ hashFiles('composer.lock') }}-${{ matrix.php }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: pcov

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --ansi

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Cache dependencies
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache PHPStan result cache
        uses: actions/cache@v4
        with:
          path: .phpstan.cache
          key: "phpstan-result-cache-${{ github.run_id }}"
          restore-keys: |
            phpstan-result-cache-

      - name: Generate key
        run: php artisan key:generate

      - name: Setup database
        run: touch storage/database.sqlite

      - name: Install chrome driver
        run: php artisan dusk:chrome-driver

      - name: Run migrations
        run: php artisan migrate --seed

      - name: Execute tests
        run: composer test

      - name: Upload Laravel Logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "log-php${{ matrix.php }}"
          path: storage/logs/*
